apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: "tenant2-release"
  namespace: "flux-system"
spec:
  interval: "5m"
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
  postBuild:
    substitute:
      tenantGuid: "tenant2"
      
