apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ${tenantGuid}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # the port exposed to the cluster
      targetPort: 80 # the port exposed by the pod
  type: ClusterIP
